import { Veiculo } from "./Veiculo.js"
import { Carro } from "./Carro.js"
import { Moto } from "./Moto.js"

const carro = new Veiculo('Uno', 'Preto', 60)
console.log(carro)
carro.acelerar()
carro.acelerar()
carro.acelerar()
carro.acelerar()
carro.acelerar()
carro.acelerar()
carro.acelerar()
carro.acelerar()
carro.acelerar()
carro.acelerar()
carro.acelerar()
carro.acelerar()
carro.acelerar()
carro.pintar('Azul')
const carro1 = new Carro('Gol', 'Azul', 110)
console.log(carro1)
carro1.acelerar()
carro1.acelerar()
carro1.acelerar()
carro1.acelerar()
carro1.acelerar()
carro1.acelerar()
carro1.acelerar()
carro1.acelerar()
carro1.acelerar()
carro1.acelerar()
carro1.acelerar()
carro1.acelerar()
carro1.acelerar()
carro1.acelerar()
carro1.acelerar()
carro1.acelerar()
carro1.limparParabrisa()
carro1.pintar('Verde')
const moto = new Moto('CG', 'Vermelha', 120)
console.log(moto)
moto.acelerar()
moto.acelerar()
moto.acelerar()
moto.acelerar()
moto.acelerar()
moto.acelerar()
moto.acelerar()
moto.acelerar()
moto.acelerar()
moto.acelerar()
moto.acelerar()
moto.acelerar()
moto.acelerar()
moto.pintar('Roxo')